### ISSUE TITLE
Detecting coffee maker buzzer

### ISSUE THREAD

**Issue by y8s** [benjaminchodroff/alarmBeepDetect#2]
Benjamin,
I'm trying to detect a coffee maker end buzzer. It beeps 4 times and I can USUALLY get it to trigger the alarm, but unfortunately the buzzer is not a straight sinewave output. Generally frequency detect shows 2500 Hz but not always. And it doesn't always catch all of the beeplength blips. Sometimes 2, sometimes 4. 

I'm curious if you have any advice or restructuring of the code that might help. The beeps are fairly loud and in close proximity to the microphone. 

Otherwise the code is pretty awesome and works great with my nodered implementation.

I've attached the wav of the beeps in case you're interested in looking into it.

Matt
[coffee beeps.zip](https://github.com/benjaminchodroff/alarmBeepDetect/files/4395148/coffee.beeps.zip)

**Comment by benjaminchodroff** [comment]
I'd suggest starting here. 

SENSITIVITY=1
TONE=2505 # Measured with audacity -> analyze -> plot spectrum -> find largest peak
BANDWIDTH=30 # Just a buffer - can reduce to avoid false detection
beeplength=6 # ~350ms length / 46ms blip, and round down and subtract one to be safe
alarmlength=3 # 4 beeps expected, but let's aim to catch three of them positively
resetlength= 4 # ~230ms length / 46ms blip, and round down and subtract one to be safe
clearlength= 30
